import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GlassPane from "@/components/glass-pane";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-screen w-screen rainbow-mesh p-6">
          <GlassPane className="w-full h-full flex items-center justify-center">
            {children}
          </GlassPane>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
